apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: honeytrap-ai-data
  namespace: honeytrap
  labels:
    app.kubernetes.io/name: honeytrap-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
