apiVersion: v1
kind: Service
metadata:
  name: honeytrap-ai
  namespace: honeytrap
  labels:
    app.kubernetes.io/name: honeytrap-ai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: honeytrap-ai
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: ftp
      port: 21
      targetPort: 21
      protocol: TCP
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
    - name: health
      port: 9200
      targetPort: 9200
      protocol: TCP
